### ISSUE TITLE
Can't seem to get the plugin to work. *Most Likely a User Error*

### ISSUE THREAD

**Issue by Noxtis** [GaelicThunder/Experience-Plugin-Pwnagotchi#13]
I'm new to the whole Pwnagotchi so I've been learning as much as I could in 24 hours. I managed to get the Age Plugin that you've referenced, and the Hat one to work (Still not detecting the battery level sadly, but it's running)

I still can't seem to get the EXP to load, It's showing up in the proper folder, but when I go to manually activate it, it doesn't seem to activate, even when using the WEBUI as well with the toggle button.

Hopefully I can get some clarification, as I do think I'm doing something wrong.

**Comment by GaelicThunder** [comment]
I must admit, im not using the Pwnagotchi in a while (a year prolly).
That being sad, let's try debugging it.
Have you tried following the setup step by step? (Using the config.toml and restarting it?)

**Comment by Noxtis** [comment]
Yes, I’ve tried via the config file as well as restarting via WebUI and manual reset.

**Comment by tacticalpidgeon** [comment]
Having the same issue

Error:
NameError: name 'false' is not defined

**Comment by GaelicThunder** [comment]
Sadly, i dont have a Pwnagotchi around to test...
The error is because there is a "false" somewhere (which in python does not exist, its "False" with the capital) but, looking at the code, i can't find it, so the only idea i've got at the moment, could be that it get it in some json.
You could try doing a (Super) ugly stuff and add:
`false = False`
in this [line]( https://github.com/GaelicThunder/Experience-Plugin-Pwnagotchi/blob/f456040de4951de1e6ab3fcb4453d42a7da362d1/exp.py#L26) or somewhere nearby a json load.
In this case, if a json get loaded and pass into the interpreter (which is what i think it is doing for some reason), it shouldnt give you that error.

[This StackOverflow explains it better](https://stackoverflow.com/questions/24791854/python-json-nameerror-name-false-is-not-defined)

**Comment by GaelicThunder** [comment]
Also, im sorry @Noxtis for not answering, i totally forgot. Did you debug it in the end?
